config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "groups#index"
  resources :users, only: [:index]
  resources :groups, only: [:create,:new, :edit, :update] do
    resources :chats, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :group

  validates :text_or_image, presence: true
  validates :group_id, presence: true
  validates :user_id, presence: true

  mount_uploader :image, ImageUploader

  private
  def text_or_image
    text.presence || image.presence
  end

end

app/models/group.rb
class Group < ApplicationRecord

  validates :name, presence: true

  has_many :users,through: :user_groups
  has_many :user_groups
  has_many :chats

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # has_many chats
  has_many :groups,through: :user_groups
  has_many :user_groups
  has_many :chats

  scope :name_search,->(current_user,keyword){ where('name LIKE(?)',"%#{keyword}%").where.not( id: current_user )}
end

app/models/user_group.rb
class UserGroup < ApplicationRecord

  belongs_to :user
  belongs_to :group

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :index, :create]

  def index
    @groups = current_user.groups
    @group = Group.find(params[:group_id])
    @chat = Chat.new
    @chats = @group.chats.order('created_at ASC')
    @users = @group.users

    respond_to do |format|
      format.html
      format.json { @reload_chat = @group.chats.where('id > ?', params[:num])}
    end
  end

  def new
    @chat = Chat.new
    @user = current_user.id
  end

  def create
    @group = Group.find(params[:group_id])
    @chat = current_user.chats.new(chat_params)
    if @chat.save
      respond_to do |format|
        format.html { redirect_to group_chats_path(@group) }
        format.json
      end
    else
      flash[:alert] = 'メッセージの入力に失敗しました'
      render :index
    end
  end

  def chat_params
    params.require(:chat).permit(:text, :image, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def show
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました。'
    else
      flash[:alert] = 'グループの作成に失敗しました'
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path, notice: 'グループを編集しました。'
    else
      flash[:alert] = 'グループの編集に失敗しました'
      render :edit
    end
  end

  def search
  end

  private
  def group_params
    params.require(:group).permit(:name, {user_ids: []})
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.where('name LIKE(?)', "%#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chat/index.html.haml
%body
  .flash
    .wrapper
      .side-bar
        .header
          %h3.header__name nmatsuda
          %ul.header__lists
            %li.list<
              %i.fa.fa-pencil-square-o
            %li.list<
              %i.fa.fa-cog
        .groups
          .group
            %ul
              %li.group__name<
                グループ1
                %p.chat__name
                  Hello!
              %li.group__name<
                グループ1
                %p.chat__name
                  Hello!
      .chat
        .header
          .left-header
            .left-header__title
              matsudaグループ
              %ul.left-header__members
                Members: 
                %li.member
                  matsuda
                %li.member
                  taro
          .right-header
            Edit
        .messages_group
          .messages
            .upper-message
              .upper-message__user-name
              matsuda
              .upper-message__date
              2017/08/24 06:57
            .lower-message
              .lower-message__content
                hello!
          .messages
            .upper-message
              .upper-message__user-name
              taro
              .upper-message__date
              2017/08/24 06:57
            .lower-message
              .lower-message__content
              hello!
        .form
          .js-form#new_message
            %input.form__message#message_content{ placeholder: "Please enter your message" }
              .form__mask
                %label.form__mask__image
                  %i.fa.fa-picture-o
            %input.form__submit{ type: "submit", value: "SEND" }

app/views/chats/_chat.html.haml
.messages{ 'data-messages-id': chat.id }
  .upper-message
    .upper-message__user-name
      = chat.user.name
    .upper-message__date
      = chat.created_at
  .lower-message
    .lower-message__content
      = chat.text
  - if chat.image.present?
    .lower-message__image
      = image_tag chat.image.url

app/views/chats/_users.html.haml
= users.name

app/views/chats/index.html.haml
%body
  .flash
    .wrapper
      .side-bar
        .header
          %h3.header__name nmatsuda
          %ul.header__lists
            %li.list<
              = link_to new_group_path do
                %i.fa.fa-pencil-square-o
            %li.list<
              = link_to edit_user_registration_path (current_user.id) do
                %i.fa.fa-cog.fa-spin
        .groups
          = render @groups

      .chat
        .header
          .left-header
            .left-header__title
              = "#{@group.name}"
              %ul.left-header__members
                Members:
                = render partial: "users", collection: @users 

          .right-header
            = link_to edit_group_path(@groups) do
              Edit
        .messages_group
          = render @chats
        .form
          = form_for @chat, url: group_chats_path(@group), html: {class: 'js-form', id: 'new_comment'} do |f|
            = f.text_field :text, placeholder: "Please enter your message", class: 'form__message'
            .form__mask
              %label
                = f.file_field :image , class: 'file_none'
                %i.fa.fa-picture-o.form__mask__image
            = f.hidden_field :group_id, value: "#{@group.id}"
            = f.submit "SEND" , class: 'form__submit'

app/views/groups/_group.html.haml
.group
  =link_to group_chats_path(group) do
    %p.group__name #{group.name}
  - if group.chats.exists?
    %p.group__chat #{group.chats.last.text}
  - else
    %p.group__chat まだメッセージはありません。

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for @group, html: {id: 'edit_chat_group_22.edit_chat_group', :method => "patch"} do |f|
    - if @group.errors.any?
      .chat-group-form__errors
        = "#{@group.errors.count}件のエラーがあります。"
        .ul
        - @group.errors.full_messages.each do |msg|
          .li
            = msg


    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "チャットメンバー" , class: chat-group-form__label
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit "Save" , class:chat-group-form__action-btn

app/views/groups/index.html.haml
%body
  .flash
    .wrapper
      .side-bar
        .header
          %h3.header__name nmatsuda
          %ul.header__lists
            %li.list<
              = link_to new_group_path do
                %i.fa.fa-pencil-square-o
            %li.list<
              %i.fa.fa-cog
        .groups
          .group
            = render @groups

      .chat
        .header
          .left-header
            .left-header__title
              matsudaグループ
              %ul.left-header__members
                Members: 
                %li.member
                  matsuda
                %li.member
                  taro
          .right-header
            Edit
        .messages_group
          .messages
            .upper-message
              .upper-message__user-name
              matsuda
              .upper-message__date
              2017/08/24 06:57
            .lower-message
              .lower-message__content
                hello!
          .messages
            .upper-message
              .upper-message__user-name
              taro
              .upper-message__date
              2017/08/24 06:57
            .lower-message
              .lower-message__content
              hello!
        .form
          .js-form#new_message
            %input.form__message#message_content{ placeholder: "Please enter your message" }
              .form__mask
                %label.form__mask__image
                  %i.fa.fa-picture-o
            %input.form__submit{ type: "submit", value: "SEND" }

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group, html: {id: 'new_chat_group.new_chat_group'} do |f|
    - if @group.errors.any?
      .chat-group-form__errors
        = "#{@group.errors.count}件のエラーがあります。"
        .ul
        - @group.errors.full_messages.each do |msg|
          .li
            = msg

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_name"} グループ名
      .chat-group-form__field--right
        = f.text_field :name, autofocus: true, class: "chat-group-form__input"

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          = f.text_field :name, html: {id: 'user-search-field'}, class: 'chat-group-form__input', placeholder: "追加したいユーザー名を入力してください"
        #user-search-result

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
      .chat-group-form__field--right
        #chat-group-users
          #chat-group-user-22.chat-group-user.clearfix
            %input{:name => "chat_group[user_ids][]", :type => "hidden", :value => "22"}/
            %p.chat-group-user__name
          #member-search-result

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        %input.chat-group-form__action-btn{"data-disable-with" => "Save", :name => "commit", :type => "submit", :value => "Save"}/

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield